/* Auto-generated by scripts/generate-config.js — edit .env, do not edit by hand */
window.SITE_CONFIG = {
    "apiBaseUrl": "https://mallmanbackend.footballive90.com/api",
    "androidUrl": "",
    "iosUrl": "",
    "pwaUrl": "https://footballive90.com",
    "appUrl": "https://footballive90.com",
    "contactEmail": "support@footballive90.com",
    "contactPhone": "",
    "instagramUrl": "",
    "telegramUrl": "",
    "twitterUrl": "",
    "faviconUrl": "https://footballive90.com/icons/icon-72x72.png",
    "copyrightYear": "2026"
};
