/* Auto-generated by scripts/generate-config.js — edit .env, do not edit by hand */
window.SITE_CONFIG = {
    "apiBaseUrl": "https://mallmanbackend.footballive90.com/api",
    "androidUrl": "",
    "iosUrl": "",
    "pwaUrl": "https://footballive90.com",
    "appUrl": "https://footballive90.com",
    "contactEmail": "support@footballive90.com",
    "contactPhone": "",
    "contactAddress": "",
    "contactAddressFa": "",
    "whatsappUrl": "",
    "instagramUrl": "",
    "telegramUrl": "",
    "twitterUrl": "",
    "faviconUrl": "icons/favicon.png",
    "logoUrl": "icons/logo.png",
    "assetVersion": "20260703",
    "copyrightYear": "2026"
};
