#!/usr/bin/env node
/**
 * Reads .env and writes js/site-config.js for the static landing site.
 * Usage: node scripts/generate-config.js
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const ENV_FILE = path.join(ROOT, '.env');
const OUT_FILE = path.join(ROOT, 'js', 'site-config.js');

const DEFAULTS = {
  apiBaseUrl: 'https://mallmanbackend.footballive90.com/api',
  androidUrl: '',
  iosUrl: '',
  pwaUrl: 'https://footballive90.com',
  appUrl: 'https://footballive90.com',
  contactEmail: 'support@footballive90.com',
  contactPhone: '',
  instagramUrl: '',
  telegramUrl: '',
  twitterUrl: '',
  faviconUrl: 'https://footballive90.com/icons/icon-72x72.png',
  copyrightYear: String(new Date().getFullYear()),
};

const ENV_MAP = {
  SITE_API_BASE_URL: 'apiBaseUrl',
  SITE_ANDROID_URL: 'androidUrl',
  SITE_IOS_URL: 'iosUrl',
  SITE_PWA_URL: 'pwaUrl',
  SITE_APP_URL: 'appUrl',
  SITE_CONTACT_EMAIL: 'contactEmail',
  SITE_CONTACT_PHONE: 'contactPhone',
  SITE_INSTAGRAM_URL: 'instagramUrl',
  SITE_TELEGRAM_URL: 'telegramUrl',
  SITE_TWITTER_URL: 'twitterUrl',
  SITE_FAVICON_URL: 'faviconUrl',
  SITE_COPYRIGHT_YEAR: 'copyrightYear',
};

function loadEnv(filePath) {
  if (!fs.existsSync(filePath)) return {};
  const out = {};
  fs.readFileSync(filePath, 'utf8').split(/\r?\n/).forEach((line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return;
    const eq = trimmed.indexOf('=');
    if (eq === -1) return;
    const key = trimmed.slice(0, eq).trim();
    let val = trimmed.slice(eq + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  });
  return out;
}

const env = loadEnv(ENV_FILE);
const config = { ...DEFAULTS };

Object.entries(ENV_MAP).forEach(([envKey, cfgKey]) => {
  if (env[envKey] !== undefined && env[envKey] !== '') {
    config[cfgKey] = env[envKey];
  }
});

const content = `/* Auto-generated by scripts/generate-config.js — edit .env, do not edit by hand */\nwindow.SITE_CONFIG = ${JSON.stringify(config, null, 4)};\n`;

fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
fs.writeFileSync(OUT_FILE, content, 'utf8');
console.log('Wrote', OUT_FILE);
